/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mapbox_g2o_SparseOptimizer */

#ifndef _Included_com_mapbox_g2o_SparseOptimizer
#define _Included_com_mapbox_g2o_SparseOptimizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mapbox_g2o_SparseOptimizer
 * Method:    nativeCreateOptimizationAlgo
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_mapbox_g2o_SparseOptimizer_nativeCreateOptimizationAlgo
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_mapbox_g2o_SparseOptimizer
 * Method:    nativeCreateSparseOptimizer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_mapbox_g2o_SparseOptimizer_nativeCreateSparseOptimizer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_mapbox_g2o_SparseOptimizer
 * Method:    nativeDestroySparseOptimizer
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_mapbox_g2o_SparseOptimizer_nativeDestroySparseOptimizer
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_mapbox_g2o_SparseOptimizer
 * Method:    nativeOptimize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_mapbox_g2o_SparseOptimizer_nativeOptimize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_mapbox_g2o_SparseOptimizer
 * Method:    nativeAddVertex
 * Signature: (JJDDDZ)V
 */
JNIEXPORT void JNICALL Java_com_mapbox_g2o_SparseOptimizer_nativeAddVertex
  (JNIEnv *, jclass, jlong, jlong, jdouble, jdouble, jdouble, jboolean);

/*
 * Class:     com_mapbox_g2o_SparseOptimizer
 * Method:    nativeAddEdgeSE2
 * Signature: (JJJDDD[D)V
 */
JNIEXPORT void JNICALL Java_com_mapbox_g2o_SparseOptimizer_nativeAddEdgeSE2
  (JNIEnv *, jclass, jlong, jlong, jlong, jdouble, jdouble, jdouble, jdoubleArray);

/*
 * Class:     com_mapbox_g2o_SparseOptimizer
 * Method:    nativeAddEdgeXY
 * Signature: (JJJDD[D)V
 */
JNIEXPORT void JNICALL Java_com_mapbox_g2o_SparseOptimizer_nativeAddEdgeXY
  (JNIEnv *, jclass, jlong, jlong, jlong, jdouble, jdouble, jdoubleArray);

/*
 * Class:     com_mapbox_g2o_SparseOptimizer
 * Method:    nativeGetPose
 * Signature: (JJ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_mapbox_g2o_SparseOptimizer_nativeGetPose
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
